export const GET_NOTE_REQUEST="GET_NOTE_REQUEST"
export const GET_NOTE_SUCCESS="GET_NOTE_SUCCESS"
export const GET_NOTE_FAILURE="GET_NOTE_FAILURE"

export const ADD_MOVIE_REQUEST="ADD_MOVIE_REQUEST"
export const ADD_MOVIE_SUCCESS="ADD_MOVIE_SUCCESS"
export const ADD_MOVIE_FAILURE="ADD_MOVIE_FAILURE"















